version: "2.4"
services:

  prometheus:
    image: prom/prometheus:v2.11.1
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/:/etc/prometheus/

  grafana:
    image: grafana/grafana:7.0.6
    environment:
      GF_INSTALL_PLUGINS: grafana-piechart-panel
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
